### PR TITLE
adding ksm pricing

### PR DESCRIPTION
**Pull request by poppyseedDev**
KSM constants: https://github.com/polkadot-fellows/runtimes/blob/main/relay/kusama/constants/src/lib.rs

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
Hey!
thanks for the PR, 
Just for the sake of readability please create a new file called `kusama.js` and then export the deposit as

```js
import { deposit as kusamaDeposit } from './kusama'

```

Thanks!

**Comment by poppyseedDev** [comment]
Added a results section + separated files

**Comment by vikiival** [comment]
> Added a results section + separated files

Just for the sake of readability please create a new file called kusama.js and then export the deposit as

```
import { deposit as kusamaDeposit } from './kusama'
```

Thanks

**Comment by poppyseedDev** [comment]
pls merge so I can show the results section to Joe, if you want to correct minor changes in how functions are named you can do that quickly yourself afterwards and point tag me in the commit, so that we don't have issues in the future.

**Review by vikiival — APPROVED** [review]
Doable

**Pull request merged**
